### ISSUE TITLE
Feature request: textarea for Javascript entry.

### ISSUE THREAD

**Issue by burque505** [nodebotrpa/editor#1]
This is a fantastic project, thank you so much. I would like a larger field to enter Javascript in if possible, though it works fine as is.
My idea for 'nbr-web-execute-script.html:
`    <div class="form-row">
        <label for="node-input-script"><i class="icon-tag"></i> Script</label><br>
        <textarea id="node-input-script" rows = "15" cols = "50" placeholder="Enter javascript code"></textarea>
    </div>`

**Comment by nodebotrpa** [comment]
Hi @burque505,

Thanks for your advice. Source code is updated and uploaded to npm. 

    <div class="form-row">
        <label for="node-input-script"><i class="icon-tag"></i> Script</label>
        <textarea class="form-control" id="node-input-script" rows="5" style="width:70%" placeholder="Enter javascript code"></textarea>
    </div>
